import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/*
        A fixed-height shell rather than a growing one. `min-h-full` let the
        body grow past the viewport, which meant a panel asking for `h-full` or
        `flex-1` had no definite height to resolve against and simply ran off
        the bottom of the screen. Bounding it here is what lets a page scroll
        its own regions — each one owns an `overflow-y-auto`, so the document
        itself never scrolls.
      */}
      <body className="flex h-dvh flex-col overflow-hidden">
        <nav className="flex shrink-0 gap-4 border-b border-border px-6 py-3 font-sans text-sm">
          <Link href="/" className="text-muted-foreground hover:text-foreground">
            Home
          </Link>
          <Link href="/clio" className="text-muted-foreground hover:text-foreground">
            Clio
          </Link>
          <Link href="/matters" className="text-muted-foreground hover:text-foreground">
            Matters
          </Link>
          <Link href="/chat" className="text-muted-foreground hover:text-foreground">
            Case chat
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
